#ifndef C4D_SYMBOLS
#define C4D_SYMBOLS

enum {

    GROUP_MAIN = 10000,
    STATIC_STATUS,
    BUTTON_UNDO,
    BUTTON_REDO,
    BUTTON_SEND,
    BUTTON_SEND_TOOLTIP,
    TEXT_SCRIPT,

    GROUP_TRACEBACK,
    TREE_TRACEBACK,
    BUTTON_CLOSE_TRACEBACK,

    MENU_FILE,
    MENU_FILE_OPEN,
    MENU_FILE_SAVETO,

    MENU_VIEW,
    MENU_VIEW_TRACEBACK,

    MENU_HELP,
    MENU_HELP_ABOUT,

    ABOUT_LINE1,
    ABOUT_LINE2,
    ABOUT_LINE3,

    IDC_SCRIPT_EDITOR,
    IDC_SCRIPT_EDITOR_HELP,
    IDC_CODE_OK,
    IDC_NO_TRACEBACK,
};

#endif /* C4D_SYMBOLS */