#ifndef C4D_SYMBOLS
#define C4D_SYMBOLS

enum {

    GROUP_MAIN = 10000,
    STATIC_STATUS,
    BUTTON_SEND,
    BUTTON_SEND_TOOLTIP,
    TEXT_SCRIPT,

    GROUP_TRACEBACK,
    TREE_TRACEBACK,
    BUTTON_CLOSE_TRACEBACK,

    IDC_SCRIPT_EDITOR,
    IDC_SCRIPT_EDITOR_HELP,
    IDC_CODE_OK,
};

#endif /* C4D_SYMBOLS */